<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-NRV3P3I" ignored="3" name="Default test(failed)" tests="2" failures="2" timestamp="19 Mar 2021 06:00:14 GMT" time="0.105" errors="0">
  <testcase name="test3" time="0.024" classname="org.rerunTest.DemoTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerunTest.DemoTest.test3(DemoTest.java:40)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.003" classname="org.rerunTest.DemoTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerunTest.DemoTest.test1(DemoTest.java:16)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.0" classname="org.rerunTest.DemoTest">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase name="test4" time="0.0" classname="org.rerunTest.DemoTest">
    <ignored/>
  </testcase> <!-- test4 -->
  <testcase name="test5" time="0.0" classname="org.rerunTest.DemoTest">
    <ignored/>
  </testcase> <!-- test5 -->
</testsuite> <!-- Default test(failed) -->
